---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
‘Twas brillig, and the slithy toves 

   Did gyre and gimble in the wabe;
   
All mimsy were the borogoves,

   And the mome raths outgrabe.

“Beware the Jabberwock, my son 

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Oh, give us pleasure in the flowers to-day;

And give us not to think so far away

As the uncertain harvest; keep us here

All simply in the springing of the year.


Oh, give us pleasure in the orchard white,

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,

Shining with all his might:

He did his very best to make

The billows smooth and bright--

And this was odd, because it was

The middle of the night.

The moon was shining sulkily,

Because she thought the sun

Had got no business to be there

After the day was done--

"It's very rude of him," she said,

"To come and spoil the fun!"

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
A million stars up in the sky.

One shines brighter - I can't deny.

A love so precious, a love so true,

a love that comes from me to you.

The angels sing when you are near.

Within your arms I have nothing to fear.

You always know just what to say. 

Just talking to you makes my day.

I love you, honey, with all of my heart.

Together forever and never to part.


